name: omnix
description: Application OMNIX par DEM Productions (DLS 26 Style)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  http: ^1.2.2
  url_launcher: ^6.3.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

# Configuration de l'icône OMNIX
flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/images/icon.png"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true