// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw_nFAUlCi_iqIUYElvkZofeEnglepzw4',
    appId: '1:350950036438:web:f6b3180a3d8358d3cb8a77',
    messagingSenderId: '350950036438',
    projectId: 'omnix-9e43c',
    authDomain: 'omnix-9e43c.firebaseapp.com',
    databaseURL: 'https://omnix-9e43c-default-rtdb.firebaseio.com',
    storageBucket: 'omnix-9e43c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB2quXFMFy_jbtF8qB_4BqBUL1zFv5WRY',
    appId: '1:350950036438:android:e10e516caff73811cb8a77',
    messagingSenderId: '350950036438',
    projectId: 'omnix-9e43c',
    databaseURL: 'https://omnix-9e43c-default-rtdb.firebaseio.com',
    storageBucket: 'omnix-9e43c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVT7oahOvcNVxrNfoBF8mlvCrxVCPAbDU',
    appId: '1:350950036438:ios:27a9a014d92bc161cb8a77',
    messagingSenderId: '350950036438',
    projectId: 'omnix-9e43c',
    databaseURL: 'https://omnix-9e43c-default-rtdb.firebaseio.com',
    storageBucket: 'omnix-9e43c.firebasestorage.app',
    iosClientId: '350950036438-f32emrlmc63lvq2c3db6kd6942dd1opr.apps.googleusercontent.com',
    iosBundleId: 'com.demproductions.omnix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVT7oahOvcNVxrNfoBF8mlvCrxVCPAbDU',
    appId: '1:350950036438:ios:27a9a014d92bc161cb8a77',
    messagingSenderId: '350950036438',
    projectId: 'omnix-9e43c',
    databaseURL: 'https://omnix-9e43c-default-rtdb.firebaseio.com',
    storageBucket: 'omnix-9e43c.firebasestorage.app',
    iosClientId: '350950036438-f32emrlmc63lvq2c3db6kd6942dd1opr.apps.googleusercontent.com',
    iosBundleId: 'com.demproductions.omnix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw_nFAUlCi_iqIUYElvkZofeEnglepzw4',
    appId: '1:350950036438:web:16de6ddb03463d4fcb8a77',
    messagingSenderId: '350950036438',
    projectId: 'omnix-9e43c',
    authDomain: 'omnix-9e43c.firebaseapp.com',
    databaseURL: 'https://omnix-9e43c-default-rtdb.firebaseio.com',
    storageBucket: 'omnix-9e43c.firebasestorage.app',
  );
}
